name: CI

on:
  push:
    branches:
      - "main"
      - "dev/**"
      - "releases/**"
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        java-lts: [8, 17, 21]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-lts }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Running check lifecycle
        run: ./gradlew check

      - name: Coveralls code coverage
        uses: coverallsapp/github-action@v2
        with:
          format: jacoco
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  dependency-submission:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-lts: [ 8, 17, 21 ]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-lts }}
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
