name: CI

on:
  push:
    branches:
      - "main"
      - "releases/**"
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        java-lts: [11, 17, 21]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-lts }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Running check lifecycle
        run: ./gradlew check

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Build with Jekyll
        run: bundle exec jekyll build

  dependency-submission:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-lts: [11, 17, 21]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-lts }}
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
